// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9PDch5T-zUr1fL73-st2DbFaKuywVJOY',
    appId: '1:65865440662:web:06527000a6b539c88591b7',
    messagingSenderId: '65865440662',
    projectId: 'cinebyte-network-application',
    authDomain: 'cinebyte-network-application.firebaseapp.com',
    storageBucket: 'cinebyte-network-application.appspot.com',
    measurementId: 'G-8MZFETCHFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA21t2a-XP50S7MMO5oSpGFm4rlOaXRKDQ',
    appId: '1:65865440662:android:1c71a5721df861d58591b7',
    messagingSenderId: '65865440662',
    projectId: 'cinebyte-network-application',
    storageBucket: 'cinebyte-network-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHzMeo6JGI8xVr-rTNz2U6swD6570dZkM',
    appId: '1:65865440662:ios:9e6972be21f096c48591b7',
    messagingSenderId: '65865440662',
    projectId: 'cinebyte-network-application',
    storageBucket: 'cinebyte-network-application.appspot.com',
    iosBundleId: 'com.example.simpleTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHzMeo6JGI8xVr-rTNz2U6swD6570dZkM',
    appId: '1:65865440662:ios:9e6972be21f096c48591b7',
    messagingSenderId: '65865440662',
    projectId: 'cinebyte-network-application',
    storageBucket: 'cinebyte-network-application.appspot.com',
    iosBundleId: 'com.example.simpleTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9PDch5T-zUr1fL73-st2DbFaKuywVJOY',
    appId: '1:65865440662:web:55a743acb11723d48591b7',
    messagingSenderId: '65865440662',
    projectId: 'cinebyte-network-application',
    authDomain: 'cinebyte-network-application.firebaseapp.com',
    storageBucket: 'cinebyte-network-application.appspot.com',
    measurementId: 'G-5XWN2P350T',
  );
}
